### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by gabek** [gabek/samcloud-updater#2]
goroutine 1 [running]:
panic(0x7f3940, 0xc82000a130)

/usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.fullAudioFromPreviewURL(0x0, 0x0, 0x0, 0x0)

 /home/gabek/src/go/src/github.com/gabek/samcloud-updater/mixcloud.go:70 +0x1f4
main.detailsForMixcloudURL(0xc820200000, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0

main.processMixcloudURL(0xc820200000, 0x25, 0x0)
/home/gabek/src/go/src/github.com/gabek/samcloud-updater/mixcloud.go:33 +0x40

**Comment by gabek** [comment]
This is due to `server := previewURL[0 : length-1]`

We should skip any mixcloud entries with no previewURLs.
